services:
  postgres:
    image: postgres:16-alpine
    container_name: users-postgres
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: users
      POSTGRES_PASSWORD: users_password
    ports:
      - "5432:5432"
    volumes:
      - users-postgres-data:/var/lib/postgresql/data
  mock-postgres:
    image: postgres:16-alpine
    container_name: mock-postgres
    environment:
      POSTGRES_DB: mocksvc
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "6432:5432"
    volumes:
      - mock-postgres-data:/var/lib/postgresql/data
  dsl-runner-postgres:
    image: postgres:16-alpine
    container_name: dsl-runner-postgres
    environment:
      POSTGRES_DB: dslrunner
      POSTGRES_USER: dsl
      POSTGRES_PASSWORD: pass
    ports:
      - "7432:5432"
    volumes:
      - dsl-runner-postgres-data:/var/lib/postgresql/data

volumes:
  users-postgres-data:
  mock-postgres-data:
  dsl-runner-postgres-data:
