/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/mocks/v1/mocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List mocks */
        get: {
            parameters: {
                query?: {
                    q?: string;
                    familyId?: string;
                    enabled?: boolean;
                    method?: string;
                    path?: string;
                    sort?: "updatedAtDesc";
                    limit?: number;
                    offset?: number;
                };
                header: {
                    /** @description User identifier performing the request */
                    "X-User-Id": components["parameters"]["UserId"];
                    /** @description Comma-separated roles (e.g. ADMIN) */
                    "X-Roles"?: components["parameters"]["Roles"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["Mock"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create mock */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description User identifier performing the request */
                    "X-User-Id": components["parameters"]["UserId"];
                    /** @description Comma-separated roles (e.g. ADMIN) */
                    "X-Roles"?: components["parameters"]["Roles"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        description?: string;
                        requestMatch: {
                            [key: string]: unknown;
                        };
                        responseTemplate: {
                            [key: string]: unknown;
                        };
                        enabled?: boolean;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id?: string;
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mocks/v1/mocks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get mock */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description User identifier performing the request */
                    "X-User-Id": components["parameters"]["UserId"];
                    /** @description Comma-separated roles (e.g. ADMIN) */
                    "X-Roles"?: components["parameters"]["Roles"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Mock"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete mock */
        delete: {
            parameters: {
                query?: never;
                header: {
                    /** @description User identifier performing the request */
                    "X-User-Id": components["parameters"]["UserId"];
                    /** @description Comma-separated roles (e.g. ADMIN) */
                    "X-Roles"?: components["parameters"]["Roles"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update mock */
        patch: {
            parameters: {
                query?: never;
                header: {
                    /** @description User identifier performing the request */
                    "X-User-Id": components["parameters"]["UserId"];
                    /** @description Comma-separated roles (e.g. ADMIN) */
                    "X-Roles"?: components["parameters"]["Roles"];
                };
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        description?: string | null;
                        requestMatch?: {
                            [key: string]: unknown;
                        };
                        responseTemplate?: {
                            [key: string]: unknown;
                        };
                        enabled?: boolean;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Mock"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/mocks/v1/families": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create family */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description User identifier performing the request */
                    "X-User-Id": components["parameters"]["UserId"];
                    /** @description Comma-separated roles (e.g. ADMIN) */
                    "X-Roles"?: components["parameters"]["Roles"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        primaryMockId: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            familyId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mocks/v1/families/{familyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get family */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description User identifier performing the request */
                    "X-User-Id": components["parameters"]["UserId"];
                    /** @description Comma-separated roles (e.g. ADMIN) */
                    "X-Roles"?: components["parameters"]["Roles"];
                };
                path: {
                    familyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            familyId?: string;
                            /** Format: uuid */
                            primaryMockId?: string;
                            items?: {
                                /** Format: uuid */
                                mockId?: string;
                                isPrimary?: boolean;
                                /** Format: uuid */
                                derivedFromBaseId?: string | null;
                                /** Format: uuid */
                                viaDslScriptId?: string | null;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mocks/v1/families/{familyId}/mocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add mock to family */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description User identifier performing the request */
                    "X-User-Id": components["parameters"]["UserId"];
                    /** @description Comma-separated roles (e.g. ADMIN) */
                    "X-Roles"?: components["parameters"]["Roles"];
                };
                path: {
                    familyId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        mockId: string;
                    };
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mocks/v1/families/{familyId}/primary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update family primary mock */
        patch: {
            parameters: {
                query?: never;
                header: {
                    /** @description User identifier performing the request */
                    "X-User-Id": components["parameters"]["UserId"];
                    /** @description Comma-separated roles (e.g. ADMIN) */
                    "X-Roles"?: components["parameters"]["Roles"];
                };
                path: {
                    familyId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        newPrimaryMockId: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            familyId?: string;
                            /** Format: uuid */
                            primaryMockId?: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/mocks/v1/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create generation (preview/apply) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description User identifier performing the request */
                    "X-User-Id": components["parameters"]["UserId"];
                    /** @description Comma-separated roles (e.g. ADMIN) */
                    "X-Roles"?: components["parameters"]["Roles"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        baseMockId: string;
                        /** Format: uuid */
                        dslScriptId: string;
                        dslScript: string;
                        params?: {
                            [key: string]: unknown;
                        };
                        /** @enum {string} */
                        mode: "preview" | "apply";
                    };
                };
            };
            responses: {
                /** @description Preview */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            planned?: {
                                name?: string;
                                description?: string | null;
                                requestMatch?: {
                                    [key: string]: unknown;
                                };
                                responseTemplate?: {
                                    [key: string]: unknown;
                                };
                                enabled?: boolean | null;
                            }[];
                        };
                    };
                };
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            generationId?: string;
                            status?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mocks/v1/generations/{generationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get generation */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description User identifier performing the request */
                    "X-User-Id": components["parameters"]["UserId"];
                    /** @description Comma-separated roles (e.g. ADMIN) */
                    "X-Roles"?: components["parameters"]["Roles"];
                };
                path: {
                    generationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Generation"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code?: string;
            message?: string;
        };
        Mock: {
            /** Format: uuid */
            id?: string;
            name?: string;
            description?: string | null;
            requestMatch?: {
                [key: string]: unknown;
            };
            responseTemplate?: {
                [key: string]: unknown;
            };
            enabled?: boolean;
            /** Format: uuid */
            familyId?: string | null;
            /** Format: uuid */
            createdBy?: string;
            /** Format: uuid */
            generatedBy?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            deletedAt?: string | null;
        };
        Generation: {
            /** Format: uuid */
            generationId?: string;
            /** @enum {string} */
            status?: "QUEUED" | "RUNNING" | "DONE" | "FAILED";
            /** Format: uuid */
            baseMockId?: string;
            /** Format: uuid */
            dslScriptId?: string;
            resultMockIds?: string[];
            error?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
    };
    responses: never;
    parameters: {
        /** @description User identifier performing the request */
        UserId: string;
        /** @description Comma-separated roles (e.g. ADMIN) */
        Roles: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
